---
title: "Perfil de Cargo Ayudante de Investigación"
format: html
editor: visual
---

El **Observatorio de Cohesión Social** de COES se encuentra buscando a un **ayudante de investigación** para el apoyo general de las labores del Observatorio durante el año 2025. 

**Funciones principales**

1. Apoyo en la actualización del sitio web del Observatorio, incluyendo su migración a Quarto. 
2. Apoyo en la actualización de un visualizador de Cohesión Social, alojado en el sitio web del Observatorio.
3. Apoyo logístico durante los eventos públicos del repositorio.
4. Gestión de la difusión de contenido relacionado al Observatorio, mediante el sitio web del Observatorio y sus redes sociales.
5. Apoyo en la redacción artículos o columnas para ser publicados en medios de prensa nacionales. 

**Requisitos**

- Ser estudiante de 3er año o más de la carrera de sociología 
- Manejo de bases de datos
- Conocimientos en R y Quarto.
- Manejo en Git y Github
- Conocimientos en construcción de dashboards y visualización de datos (deseable).
- Conocimiento en construcción de sitios web mediante Quarto (deseable).

**Disponibilidad**

11 horas semanales entre abril y noviembre del 2025. 

**Honorarios**

$150.000 mensuales
